# Mount creds 
extraVolumeMounts:
  - name: "azure-config-file"
    mountPath: "/etc/kubernetes"
    readOnly: true
extraVolumes:
  - name: "azure-config-file"
    secret:
      secretName: "azure-config-file"