cloudfairy_module:
  type: component
  name: docker
  displayName: "Docker from DockerHub"
  vendor: "cloudfairy"
  dependencies:
    - cloudfairy/cluster
  builder: terraform
  entry:
    local: k3d
    gcp: gcp
  interface: []
  properties:
    - name: dockerhub_image
      displayName: "DockerHub Image or Image uri (incl. tag)"
      type: string
      defaultValue: "nginx"
    - name: container_port
      displayName: "Container Ports (comma separated, i.e. 3001,1337...)"
      type: string
      defaultValue: "8080"
    - name: isexposed
      displayName: "Should the service be exposed externally?"
      type: boolean
      defaultValue: true
    - name: env_vars
      displayName: "Environment variables, comma separated (i.e. FOO=bar,BAZ=foo)"
      defaultValue: "CLOUDFAIRY=true"
      type: string
